language: nodejs
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provide: surge
  skip_cleanup: true
  domain: timer-tdd.surge.sh
  project: ./build/


on:
  branch: master